updated change-log file for v2.1.1 release
fledge-iot/fledge-gui pull request #257
Opened 2023-02-21 10:39 UTC by mshariq-nerd

2023-02-21 10:47 UTC, praveen-garg reviewed
Should be based on 2.1.1RC

2023-02-21 10:47 UTC, praveen-garg commented on docs/changelog.md
> +- Fixed
remove!

2023-02-21 11:00 UTC, praveen-garg requested changes
Invalid base.

2023-02-22 06:38 UTC, mshariq-nerd commented
closed in favour of #258

2023-02-22 06:38 UTC, closed without merging