[FOGL-4420]: Removed repeat field for manual and startup schedule
fledge-iot/fledge-gui pull request #29
Opened 2020-08-24 09:18 UTC by monika-Dianomic

2020-08-24 12:55 UTC, praveen-garg requested changes
There are few other issues too:
1) We should not see Repeat (Interval) for TIMED schedule. but Day / Time only
2) In list page, for TIMED don't show Interval Value but add a Time column as well and show Time value

2020-08-24 12:55 UTC, praveen-garg commented on src/app/components/core/scheduler/update-schedule/update-schedule.component.ts
> +    if (this.selectedScheduleTypeIndex === 1 || this.selectedScheduleTypeIndex === 4) {
better to keep `**!** (selectedScheduleTypeIndex == 2 || selectedScheduleTypeIndex == 3) to keep same as in html template.

2020-08-25 11:45 UTC, praveen-garg commented on src/app/components/core/scheduler/list-schedules/list-schedules.component.html
> +              <small *ngIf="schedule.repeat.trim() !== '00:00:00' && schedule.type !== 'TIMED'"> {{schedule.repeat.trim()}}</small>
should not this condition be,

`schedule.type !== 'INTERVAL'" && schedule.repeat.trim() !== '00:00:00' `?

2020-08-25 12:19 UTC, praveen-garg approved these changes

2020-08-26 06:45 UTC, mshariq-nerd approved these changes

2020-08-26 07:02 UTC, merged