show repeat column value and fields for TIMED schedule
fledge-iot/fledge-gui pull request #30
Opened 2020-09-03 07:12 UTC by monika-Dianomic

2020-09-03 07:15 UTC, praveen-garg requested changes

2020-09-03 07:15 UTC, praveen-garg commented on src/app/components/core/scheduler/update-schedule/update-schedule.component.html
> +            <div class="field">
not all but 2 and 3

2020-09-03 11:10 UTC, praveen-garg approved these changes

2020-09-03 11:30 UTC, mshariq-nerd approved these changes

2020-09-03 12:12 UTC, merged

2020-12-11 12:52 UTC, praveen-garg commented
fixes the issue introduced in #29