FOGL-8306: Show bell icon (patch2)
fledge-iot/fledge-gui pull request #394
Opened 2024-03-08 08:40 UTC by MonikaSharma06

2024-03-08 16:04 UTC, praveen-garg requested changes

2024-03-08 16:04 UTC, praveen-garg commented on src/app/components/core/system-alert/system-alert.component.ts
> +    return this.systemAlerts.sort((a, b) => a.urgency.localeCompare(b.urgency));
No

    const urgencyOrder = { "Critical": 0, "High": 1, "Normal": 2, "Low": 3 };
    
    // Group by urgency
    const groupedByUrgency = data.reduce((acc, item) => {
        if (!res[item.urgency]) {
            res[item.urgency] = [];
        }
        res[item.urgency].push(item);
        return res;
    }, {});

    // Sort urgency keys based on urgencyOrder
    const sortedUrgencyKeys = Object.keys(groupedByUrgency).sort((a, b) => urgencyOrder[a] - urgencyOrder[b]);
    
    // Sort each group by timestamp
    sortedUrgencyKeys.forEach(key => {
        groupedByUrgency[key].sort((a, b) => new Date(a.timestamp) - new Date(b.timestamp));
    });

2024-03-08 16:04 UTC, praveen-garg commented on src/app/components/core/system-alert/system-alert.component.ts
> +        this.alertsCount = 0;
also set this.systemAlerts = []?

2024-03-11 08:57 UTC, praveen-garg submitted a review, later dismissed

2024-03-11 08:57 UTC, praveen-garg commented on src/app/components/core/system-alert/system-alert.component.ts
> +    this.sortByKey = 'urgency';
Add an inline comment that its toggling for next action text

2024-03-11 08:57 UTC, praveen-garg commented on src/app/components/core/system-alert/system-alert.component.ts
> +    if (alerts.length === 0) {
Add inline comment and explain why is this required?

2024-03-11 08:57 UTC, praveen-garg commented on src/app/components/core/system-alert/system-alert.component.ts
> +    this.sortByKey = 'time';
Add toggling next possible action text

2024-03-11 11:21 UTC, mshariq-nerd approved these changes

2024-03-11 13:03 UTC, merged

2024-03-11 13:05 UTC, praveen-garg commented on src/app/components/core/system-alert/system-alert.component.ts
> +    if (alerts.length === 0) {
I'm still not clear on this.

2024-03-11 13:49 UTC, praveen-garg commented on src/app/components/core/system-alert/system-alert.component.ts
> +    const systemAlerts = groupedByUrgency.reduce((a, value) => a.concat(value), []);
What is the use of this? and can be directly assigned to  this.systemAlerts = ... if required? Add an inline comment

2024-03-11 13:50 UTC, praveen-garg commented on src/app/components/core/system-alert/system-alert.component.ts
> +    this.hideLoadingSpinner();
hideLoadingSpinner() should not be here.