Deprecate asset button added & per asset reading count shown in quickview
fledge-iot/fledge-gui pull request #396
Opened 2024-03-12 11:03 UTC by hemantgarg923

**Issues fixed**: 

- Show per asset reading count in quickview
- Add deprecate asset button if developer features are on
- Add icon for per asset reading count on node and also add in context menu
- Show plugin version on hover of plugin name

2024-03-14 06:31 UTC, mshariq-nerd requested changes

2024-03-14 06:31 UTC, mshariq-nerd commented on src/app/components/common/node-editor/node-editor.component.html
> +      </div>
Move this code block in a separate component and use as a child component here.

2024-03-14 06:31 UTC, mshariq-nerd commented on src/app/components/common/node-editor/custom-node/custom-node.component.ts
> +    this.flowEditorService.showItemsInQuickview.next({ showPluginConfiguration: false, showFilterConfiguration: false, showLogs: false, showReadings: true, serviceName: this.service.name });
In showItemsInQuickview  BehaviorSubject the only option that is required to open/show should be passed only. The condition checking on the quick view page can manage default value to false of other items.

2024-03-20 10:24 UTC, mshariq-nerd requested changes

2024-03-20 10:24 UTC, mshariq-nerd commented on src/app/components/common/node-editor/south/asset-tracker/asset-tracker.component.ts
> +  }
Duplicate code block. It can be avoided by Output emit event to perform action on the node-editor component for export readings.

2024-03-26 07:40 UTC, praveen-garg approved these changes

2024-03-26 07:58 UTC, mshariq-nerd approved these changes

2024-03-26 09:50 UTC, MonikaSharma06 commented on src/app/components/common/node-editor/south/asset-tracker/asset-tracker.component.ts
> +  destroy$: Subject<boolean> = new Subject<boolean>();
Is there any use of it?

2024-03-26 09:50 UTC, MonikaSharma06 commented on src/app/components/common/node-editor/south/asset-tracker/asset-tracker.component.ts
> +  @Input()service;
typecast?

2024-03-26 09:50 UTC, MonikaSharma06 commented on src/app/components/common/node-editor/south/asset-tracker/asset-tracker.component.ts
> +  @Input()isAlive;
typecast?

2024-03-26 09:50 UTC, MonikaSharma06 commented on src/app/components/common/quickview/quickview.component.ts
> +  @Input() showReadings;
typecast? boolean?

2024-03-26 10:24 UTC, MonikaSharma06 approved these changes

2024-03-26 10:42 UTC, merged