FOGL-8579_GUI: Updation as per backend changes
fledge-iot/fledge-gui pull request #405
Opened 2024-04-04 11:09 UTC by MonikaSharma06

2024-04-04 11:22 UTC, praveen-garg requested changes

2024-04-04 11:22 UTC, praveen-garg commented on src/app/components/core/system-alert/system-alert.component.ts
> +    if (message.includes('updates') || message.includes('update')) {
We should first check based on key. 

I understand the problem that service restart does not have a defined key and that still need to rely on text parsing.

2024-04-05 08:28 UTC, praveen-garg approved these changes

2024-04-05 09:37 UTC, mshariq-nerd approved these changes

2024-04-05 10:07 UTC, merged