FOGL-8783: Removed extra sytem/notifications log API calls in flow editor
fledge-iot/fledge-gui pull request #425
Opened 2024-06-04 09:05 UTC by MonikaSharma06

2024-06-05 08:15 UTC, mshariq-nerd requested changes

2024-06-05 08:15 UTC, mshariq-nerd commented on src/app/components/core/logs/notification-log/notification-log.component.ts
> +        }
By this check we are only returning from the Interval Observable but the Interval() Observable will stay active in the background. To stop the Interval Observable completely on page close we need to see how we can stop that Observable. To do that we need to unsubscribe the this.subscription.

2024-06-05 08:15 UTC, mshariq-nerd commented on src/app/components/core/logs/system-log/system-log.component.ts
> +        }
As above

2024-06-12 09:56 UTC, mshariq-nerd approved these changes

2024-06-12 10:37 UTC, hemantgarg923 approved these changes

2024-06-12 14:27 UTC, merged